-- ============================================================
-- Esquema Postgres (Supabase) — Control de Herramientas
-- Portado desde schema.sql (SQLite). Ejecutar UNA vez en el
-- SQL Editor de Supabase para crear las tablas.
-- Notas de porteo:
--   * id: GENERATED BY DEFAULT AS IDENTITY (permite insertar ids
--     explícitos durante la migración de datos).
--   * activo/cantidad/dotacion/actual: enteros 0/1 y contadores,
--     igual que en SQLite (para no tocar la lógica de la app).
--   * fecha: TEXT 'YYYY-MM-DD' (la app manda strings ISO).
--   * creado: timestamptz DEFAULT now().
-- ============================================================

CREATE TABLE IF NOT EXISTS empleados (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni     TEXT,
    nombre  TEXT NOT NULL UNIQUE,
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS almacenistas (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni     TEXT,
    nombre  TEXT NOT NULL UNIQUE,
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS condiciones (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  TEXT NOT NULL UNIQUE,
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS gondolas (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  TEXT NOT NULL UNIQUE,
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estantes (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  TEXT NOT NULL UNIQUE,
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS herramientas (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    TEXT NOT NULL UNIQUE,
    nombre    TEXT NOT NULL,
    detalle   TEXT,
    cantidad  INTEGER NOT NULL DEFAULT 0,   -- stock fisico segun inventario
    modulo    TEXT,                          -- gondola
    estante   TEXT,
    ubicacion TEXT,                          -- texto legible, se arma con gondola + estante
    activo    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS movimientos (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo           TEXT NOT NULL CHECK (tipo IN ('ENTREGA', 'DEVOLUCION')),
    fecha          TEXT NOT NULL,            -- YYYY-MM-DD
    empleado_id    INTEGER NOT NULL REFERENCES empleados(id),
    herramienta_id INTEGER NOT NULL REFERENCES herramientas(id),
    cantidad       INTEGER NOT NULL CHECK (cantidad > 0),
    condicion_id   INTEGER REFERENCES condiciones(id),
    almacenista_id INTEGER REFERENCES almacenistas(id),
    observacion    TEXT,
    creado         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mov_empleado    ON movimientos(empleado_id);
CREATE INDEX IF NOT EXISTS idx_mov_herramienta ON movimientos(herramienta_id);
CREATE INDEX IF NOT EXISTS idx_mov_fecha       ON movimientos(fecha);

-- ---- cajas de herramientas que van al campo ----

CREATE TABLE IF NOT EXISTS cajas (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    activo      INTEGER NOT NULL DEFAULT 1
);

-- dotacion: lo que la caja DEBE tener y lo que TIENE ahora
CREATE TABLE IF NOT EXISTS caja_items (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id        INTEGER NOT NULL REFERENCES cajas(id),
    herramienta_id INTEGER NOT NULL REFERENCES herramientas(id),
    dotacion       INTEGER NOT NULL DEFAULT 1 CHECK (dotacion >= 0),
    actual         INTEGER NOT NULL DEFAULT 1 CHECK (actual >= 0),
    UNIQUE (caja_id, herramienta_id)
);

-- envios al campo y retornos, con checklist de contenido
CREATE TABLE IF NOT EXISTS caja_eventos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id     INTEGER NOT NULL REFERENCES cajas(id),
    tipo        TEXT NOT NULL CHECK (tipo IN ('ENVIO', 'RETORNO')),
    fecha       TEXT NOT NULL,
    empleado_id INTEGER REFERENCES empleados(id),
    destino     TEXT,
    observacion TEXT,
    creado      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS caja_evento_items (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id         INTEGER NOT NULL REFERENCES caja_eventos(id),
    herramienta_id    INTEGER NOT NULL REFERENCES herramientas(id),
    cantidad_esperada INTEGER NOT NULL,
    cantidad_real     INTEGER NOT NULL,
    condicion_id      INTEGER REFERENCES condiciones(id),
    observacion       TEXT
);

-- auditoria de movimientos caja <-> stock del panol
CREATE TABLE IF NOT EXISTS transferencias (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha          TEXT NOT NULL,
    caja_id        INTEGER NOT NULL REFERENCES cajas(id),
    herramienta_id INTEGER NOT NULL REFERENCES herramientas(id),
    cantidad       INTEGER NOT NULL CHECK (cantidad > 0),
    direccion      TEXT NOT NULL CHECK (direccion IN
                     ('DESDE_STOCK',   -- sale del stock del panol y entra a la caja
                      'A_STOCK',       -- sale de la caja y vuelve al stock
                      'ALTA',          -- entra a la caja sin tocar el stock
                      'BAJA')),        -- sale de la caja sin tocar el stock (perdida/rota)
    observacion    TEXT,
    creado         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cev_caja    ON caja_eventos(caja_id);
CREATE INDEX IF NOT EXISTS idx_cevi_ev     ON caja_evento_items(evento_id);
CREATE INDEX IF NOT EXISTS idx_transf_caja ON transferencias(caja_id);
